/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.personDirectory;
import model.person;
/**
 *
 * @author DELL
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    personDirectory personD;
    public CreateJPanel(personDirectory personD) {
        initComponents();
        this.personD = personD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblHouse = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblHouse1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCityFocusLost(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ENTER PERSON DETAILS");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblId.setText("Person ID :");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblName.setText("Name :");

        btnAdd.setBackground(new java.awt.Color(204, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setText("ADD PERSON ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblCity.setText("City :");

        lblCommunity.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblCommunity.setText("Community :");

        lblHouse.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblHouse.setText("House :");

        lblHouse1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblHouse1.setText("Age :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHouse)
                            .addComponent(lblCommunity)
                            .addComponent(lblCity)
                            .addComponent(lblId)
                            .addComponent(lblName)
                            .addComponent(lblHouse1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtCity)
                            .addComponent(txtCommunity)
                            .addComponent(txtHouse)
                            .addComponent(txtAge)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblTitle)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouse)
                    .addComponent(txtHouse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge)
                    .addComponent(lblHouse1))
                .addGap(57, 57, 57)
                .addComponent(btnAdd)
                .addGap(137, 137, 137))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCityFocusLost
        
    }//GEN-LAST:event_txtCityFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        boolean check;
        String alphapattern = "^[a-zA-Z\\s]{1,}$";
        String numpattern = "\\d+";
        String alphanum = "^[a-zA-Z0-9\\s]+$";
        
        Pattern aP = Pattern.compile(alphapattern);
        Pattern nP = Pattern.compile(numpattern);
        Pattern an = Pattern.compile(alphanum);
        
        Matcher cM = aP.matcher(txtName.getText());
        Matcher mM = aP.matcher(txtCommunity.getText());
        Matcher ctM = aP.matcher(txtCity.getText());
        Matcher yM = an.matcher(txtHouse.getText());
        Matcher sM = nP.matcher(txtId.getText());
        Matcher sr = nP.matcher(txtAge.getText());
        
        
        if ((!cM.matches()) || (!mM.matches()) || (!ctM.matches()) || (!yM.matches())|| (!sM.matches()) || (!sr.matches()) || personD.uni(txtId.getText()) )
            {
            check=false;
            }
         
         else{
                check=true;
            }
        
        
        
        
        if (check == true){
        
            String name = txtName.getText();
            int personID = Integer.parseInt(txtId.getText());
            String community = txtCommunity.getText();
            int age = Integer.parseInt(txtAge.getText());
            String city = txtCity.getText();
            String house = txtHouse.getText();

            person p = personD.addNewPerson();

            p.setPersonID(personID);
            p.setAge(age);
            p.setCity(city);
            p.setCommunity(community);
            p.setHouse(house);
            p.setName(name);

            JOptionPane.showMessageDialog(this, "Person details added to Directory !");}
        
        else {
            JOptionPane.showMessageDialog(this, "ERROR! Enter the correct value in the field.");}
        
        
        
//        txtCompany.setText("");
//        txtYear.setText("");
//        txtSerial.setText("");
//        txtModel.setText("");
//        txtSeats.setText("");
//        checkMaintain.setSelected(false);
//        checkAvail.setSelected(false);
//        txtCity.setText("");
//        

    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblHouse1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHouse;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
